export const types = {
	DO_DATA_INITIALIZATION: '[ACTION] DO_DATA_INITIALIZATION',
	GET_PRODUCTS_CAROUSEL: '[ACTION] GET_PRODUCTS_CAROUSEL',
	GET_DETAIL: '[ACTION] GET_DETAIL',
	GET_PRODUCT: '[ACTION] GET_PRODUCT',
	GET_TRANSACTIONS: '[ACTION] GET_TRANSACTIONS',
};
